version: '3'

services:
  node:
    container_name: front
    build: 
      context: ../
      dockerfile: ./deploy/Dockerfile
    volumes:
      - '../code:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
